name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy Command via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # ۱. پاک کردن فیزیکی فایل کش کانفیگ قبلی سرور برای جلوگیری از تداخل
            rm -f /home/devprofile-the25years/htdocs/the25years.devprofile.ir/current/bootstrap/cache/config.php
            
            # ۲. اجرای دیپلوی جدید
            /usr/local/bin/dploy deploy main
            
            # ۳. ورود به ریلیز جدید و چسباندن env
            cd /home/devprofile-the25years/htdocs/the25years.devprofile.ir/current
            ln -sf ../../shared/.env .env
            
            # ۴. ساخت کش جدید
            php8.2 artisan config:cache
            php8.2 artisan optimize