on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy Command via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # ۱. ابتدا دیتابیس و فایل‌های پایه را آپدیت می‌کنیم
            /usr/local/bin/dploy deploy main
            
            # ۲. ورود به پوشه ریلیز جدید که همین الان ساخته شد
            cd /home/devprofile-the25years/htdocs/www.https://the25years.devprofile.ir/current
            
            # ۳. فورس کردن لینوکس به اتصال مستقیم فایل .env اصلی به پروژه
            ln -sf ../../shared/.env .env
            
            # ۴. پاک کردن و ساخت مجدد کش با کانفیگ‌های واقعی
            php8.2 artisan optimize:clear
            php8.2 artisan config:cache