name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy Command via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # ۱. اجرای دستور دیپلوی خود کلودپنل
            /usr/local/bin/dploy deploy main
            
            # ۲. ورود به پوشه اصلی پروژه لاراول شما
            cd /home/devprofile-the25years/htdocs/the25years.devprofile.ir/current
            ln -sf ../../shared/.env .env
            # ۳. ساخت کلید لاراول (در صورتی که در فایل .env وجود نداشته باشه)
            php artisan key:generate --force
            
            # ۴. پاک کردن و بهینه‌سازی کش کانفیگ‌ها
            php artisan config:cache
            php artisan route:cache